### ISSUE TITLE
Roadmap @ 1.0.0

### ISSUE THREAD

**Issue by magicae** [yudachi/poi#1]
This is the roadmap of poi version 1.0.0.
### Proxy
  - [x] Main HTTP / HTTPS proxy
  - [x] HTTP proxy upstream supported
  - [x] Shadowsocks supported
  - [x] Modify page elements for rendering
  - [x] Cache supported
  - [x] Hack supported

### UI
  - [x] Flash player embedded
  - [x] Index UI
  - [x] Settings UI
  - [x] Vertical layout

### KanColle Components
  - [x] Ship info
  - [x] Factory info

### Plugin system
  - [x] Event system
  - [x] Plugin rules

#### Core plugin
  - [x] Ship / Equipment view https://github.com/yudachi/poi/issues/6
  - [x] Experience calculator https://github.com/yudachi/poi/issues/7

#### Further plugin plan
  - [ ] WiKi support

**Comment by magicae** [comment]
v1.0.0 released!
